### PR TITLE
Fix for TEIIDTOOLS-115 Data Services Console - Export Data Service Step 3, Green "OK"

### PR DESCRIPTION
**Pull request by elvisisking**
The feedback on git export indicates if the export succeeded or failed by using an appropriate icon. The feedback also includes descriptive text that provides the name of the data service being exported and the destination repository path.

### CODE REVIEW

**Comment by elvisisking** [comment]
Here are images of the changes to the feedback implemented by this PR: gitexportsuccessfeedback
gitexportfailedfeedback

**Comment by mdrillin** [comment]
Can we just eliminate this step (the step with the export button)?  Make the wizard one page shorter - clicking "Finish" on the page before this one would attempt the export.  If the export succeeds, show a dialog with a success message and leave the wizard.  If the export fails, show a dialog with a failure message and stay in the wizard.

**Comment by elvisisking** [comment]
Yes. I plan on working that in TEIIDTOOLS-132. I wanted to get this in just in case I couldn't get TEIIDTOOLS-132 finished in time.

**Comment by blafond** [comment]
I'm also not sure what the extra page buys us.  When demoing it seems redundant and a little clumsy to click Export (on the left of the screen), then wait for OK/Fail and then click Finish way over on the right side. 

If we need a "Test GIT" URL button that makes sense on the first page or wherever the credentials input sits.

I'm OK with leaving this where it is for now because of time constraints as long as we keep an issue open to look at it again next release.

**Comment by phantomjinx** [comment]
@mdrillin, @blafond, @elvisisking
Please do NOT eliminate the page with the export button on it. Showing dialogs in web apps is not a 'nice' way of showing errors; its bad design. Think how many websites and web apps, you have used in the past and how many of them display dialogs??

The Finish button allows the wizard to complete whether the export has been completed or not. Using Finish assumes the export is to take place, which it may not, especially if the user has not reached that point yet.

**Comment by mdrillin** [comment]
I'll ask for UX input on the design.  It just feels clunky to me to click an "Export" button on the last page (only thing on the page) to do the export - then click the finish button to exit the wizard.  IMO the Finish button should do the export.

We dont have to use dialogs.  The wizard could just complete on successful export.  And if not successful, show a message on the wizard page and stay in the wizard...

**Review by phantomjinx — APPROVED** [review]

**Pull request merged**
